import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

export interface Material {
  id: number;
  name: string;
  category: string;
  totalCarbon: number;
  functionalUnit: string;
  risScores?: {
    ris: number;
    lis: number;
  };
  pricing?: {
    costPerUnit: number;
  };
}

/**
 * Export chart element to PNG
 */
export async function exportChartToPNG(
  elementId: string,
  filename: string
): Promise<void> {
  const element = document.getElementById(elementId);
  if (!element) {
    throw new Error(`Element with id "${elementId}" not found`);
  }

  const canvas = await html2canvas(element, {
    backgroundColor: '#ffffff',
    scale: 2, // Higher resolution
  });

  const link = document.createElement('a');
  link.download = `${filename}.png`;
  link.href = canvas.toDataURL('image/png');
  link.click();
}

/**
 * Export materials data to CSV
 */
export function exportMaterialsToCSV(
  materials: Material[],
  filename: string = 'materials'
): void {
  const headers = [
    'ID',
    'Name',
    'Category',
    'Total Carbon (kg CO₂e)',
    'Functional Unit',
    'RIS',
    'LIS',
    'Cost per Unit ($)',
  ];

  const rows = materials.map(m => [
    m.id,
    m.name,
    m.category,
    m.totalCarbon.toFixed(2),
    m.functionalUnit,
    m.risScores?.ris || 0,
    m.risScores?.lis || 0,
    m.pricing?.costPerUnit.toFixed(2) || 'N/A',
  ]);

  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.join(',')),
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}.csv`);
  link.style.visibility = 'hidden';
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Export comparison report to PDF
 */
export async function exportComparisonToPDF(
  materials: Material[],
  chartElementId: string,
  filename: string = 'material-comparison'
): Promise<void> {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;

  // Title
  pdf.setFontSize(20);
  pdf.text('Material Comparison Report', margin, margin);

  // Date
  pdf.setFontSize(10);
  pdf.text(`Generated: ${new Date().toLocaleDateString()}`, margin, margin + 8);

  // Materials summary
  let yPos = margin + 20;
  pdf.setFontSize(14);
  pdf.text('Materials Compared:', margin, yPos);
  
  yPos += 8;
  pdf.setFontSize(10);
  materials.forEach((m, idx) => {
    pdf.text(
      `${idx + 1}. ${m.name} (${m.category}) - ${m.totalCarbon.toFixed(1)} kg CO₂e per ${m.functionalUnit}`,
      margin + 5,
      yPos
    );
    yPos += 6;
  });

  // Add chart image
  const chartElement = document.getElementById(chartElementId);
  if (chartElement) {
    yPos += 10;
    const canvas = await html2canvas(chartElement, {
      backgroundColor: '#ffffff',
      scale: 2,
    });
    
    const imgData = canvas.toDataURL('image/png');
    const imgWidth = pageWidth - 2 * margin;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    
    // Add new page if needed
    if (yPos + imgHeight > pageHeight - margin) {
      pdf.addPage();
      yPos = margin;
    }
    
    pdf.addImage(imgData, 'PNG', margin, yPos, imgWidth, imgHeight);
    yPos += imgHeight + 10;
  }

  // Detailed comparison table
  if (yPos + 60 > pageHeight - margin) {
    pdf.addPage();
    yPos = margin;
  }

  pdf.setFontSize(14);
  pdf.text('Detailed Comparison:', margin, yPos);
  yPos += 10;

  pdf.setFontSize(9);
  const tableHeaders = ['Material', 'Carbon', 'RIS', 'LIS', 'Cost'];
  const colWidth = (pageWidth - 2 * margin) / tableHeaders.length;

  // Table header
  tableHeaders.forEach((header, idx) => {
    pdf.text(header, margin + idx * colWidth, yPos);
  });
  yPos += 6;

  // Table rows
  materials.forEach((m) => {
    pdf.text(m.name.substring(0, 20), margin, yPos);
    pdf.text(`${m.totalCarbon.toFixed(1)}`, margin + colWidth, yPos);
    pdf.text(`${m.risScores?.ris || 0}`, margin + 2 * colWidth, yPos);
    pdf.text(`${m.risScores?.lis || 0}`, margin + 3 * colWidth, yPos);
    pdf.text(`$${m.pricing?.costPerUnit.toFixed(2) || 'N/A'}`, margin + 4 * colWidth, yPos);
    yPos += 6;
  });

  // Footer
  pdf.setFontSize(8);
  pdf.text(
    'Generated by BlockPlane Materials Explorer',
    margin,
    pageHeight - 10
  );

  pdf.save(`${filename}.pdf`);
}

/**
 * Generate shareable URL with query parameters
 */
export function generateShareableURL(params: {
  materials?: number[];
  impactWeight?: number;
  carbonWeight?: number;
  costWeight?: number;
  category?: string;
}): string {
  const baseUrl = window.location.origin;
  const searchParams = new URLSearchParams();

  if (params.materials && params.materials.length > 0) {
    searchParams.set('materials', params.materials.join(','));
  }
  if (params.impactWeight !== undefined) {
    searchParams.set('impactWeight', params.impactWeight.toString());
  }
  if (params.carbonWeight !== undefined) {
    searchParams.set('carbonWeight', params.carbonWeight.toString());
  }
  if (params.costWeight !== undefined) {
    searchParams.set('costWeight', params.costWeight.toString());
  }
  if (params.category) {
    searchParams.set('category', params.category);
  }

  return `${baseUrl}/analysis?${searchParams.toString()}`;
}

/**
 * Copy text to clipboard
 */
export async function copyToClipboard(text: string): Promise<void> {
  try {
    await navigator.clipboard.writeText(text);
  } catch (err) {
    // Fallback for older browsers
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    
    try {
      document.execCommand('copy');
    } catch (err) {
      console.error('Failed to copy text:', err);
      throw new Error('Failed to copy to clipboard');
    }
    
    document.body.removeChild(textArea);
  }
}
