-- Phase 1: insert materials (scores live in lis_ris_scores, not materials)
insert into public.materials (name, category, description, manufacturer)
values
('Hempcrete', 'insulation', 'Hemp hurd and lime binder; carbon-storing, breathable wall system', 'American Lime Technology'),
('Cross-laminated timber (CLT)', 'timber', 'Mass timber panel system; strong regional supply in Great Lakes', 'Sterling Structural'),
('Thermally modified timber', 'timber', 'Heat-treated wood; rot resistant without chemicals', 'Cambia by NFP'),
('Alkali-activated slag cement', 'cement', 'Slag-based binder; Great Lakes steel industry byproduct', 'Slag Cement Association'),
('Geopolymer concrete', 'cement', 'Fly ash and slag based; lower embodied carbon than OPC', 'PCI Geopolymer'),
('Ferrock', 'cement', 'Iron silica binder that absorbs CO2 during curing', 'Iron Shell LLC'),
('Aerogel insulation blanket', 'insulation', 'Highest R-value per inch available; ideal for cold climates', 'Aspen Aerogels'),
('Wood fiber insulation board', 'insulation', 'EPD-verified; hygroscopic; cold-climate performer', 'Gutex'),
('Hemp fiber insulation', 'insulation', 'Michigan hemp supply chain developing; non-toxic', 'Hempitecture'),
('Reclaimed structural steel', 'reclaimed', 'Strong regional supply chain in Great Lakes', 'Various'),
('Mycelium panels', 'biofabricated', 'Grown on agricultural waste; non-structural applications', 'Ecovative Design'),
('Lime-hemp plaster system', 'earth', 'Breathable; moisture regulating; carbon storing', 'American Lime Technology'),
('Straw bale construction', 'timber', 'Agricultural waste; proven cold-climate insulation system', 'Various'),
('Cellulose insulation dense pack', 'insulation', 'Recycled newsprint; proven Great Lakes cold climate performer', 'Nu-Wool'),
('Reclaimed brick', 'reclaimed', 'Abundant in Great Lakes cities; zero new embodied carbon', 'Various'),
('Biochar-amended concrete', 'cement', 'Biochar sequesters carbon within the concrete slab', 'Carbon Upcycling'),
('Agricultural fiber panels', 'insulation', 'Wheat and corn straw compressed panels; regional supply', 'Oryzite'),
('Earthen plaster systems', 'earth', 'Local clay available; extremely low embodied energy', 'American Clay'),
('Phase-change material wallboard', 'insulation', 'Thermal mass in thin profile; cold-climate benefit', 'Microtek Laboratories'),
('Vacuum insulated panels', 'insulation', 'Extreme thermal performance; fragile; handle with care', 'Va-Q-tec'),
('Recycled concrete aggregate', 'reclaimed', 'Crushed demolition waste; high local availability', 'Various'),
('MgO board', 'cladding', 'Magnesium oxide; fire resistant; no silica dust', 'Magnum Board'),
('Carbon-cured concrete blocks', 'cement', 'CO2 mineralized during curing process', 'CarbonCure Technologies'),
('Cork insulation board', 'insulation', 'Renewable bark harvest; acoustic and thermal performance', 'Amorim Cork Composites'),
('Bamboo structural composites', 'timber', 'High strength; not grown regionally but carbon positive', 'MOSO International'),
('Algae biopolymer panels', 'biofabricated', 'Great Lakes algae potential; early R&D stage', 'Algaeing'),
('Self-healing concrete', 'cement', 'Bacteria or polymer triggered crack repair', 'Basilisk'),
('Natural hydraulic lime NHL', 'earth', 'Flexible binder; compatible with historic masonry', 'St Astier'),
('Structural insulated panels SIP', 'insulation', 'Proven cold-climate airtight system', 'Premier SIPs'),
('Reclaimed dimensional lumber', 'reclaimed', 'Abundant in Midwest building stock', 'Various'),
('Mass plywood panels MPP', 'timber', 'Lighter CLT alternative; emerging Great Lakes supply', 'Freres Lumber'),
('Acetylated wood Accoya', 'timber', 'Chemically modified; Class 1 durability without biocides', 'Accoya'),
('Densified wood composites', 'timber', 'High compressive strength; emerging EPD data', 'Various'),
('Myco-composite insulation', 'biofabricated', 'Mycelium grown on agricultural waste byproduct', 'Ecovative Design'),
('Belite calcite clinker cement', 'cement', '60 percent lower kiln temperature than OPC', 'Calucem'),
('Magnesium oxide cement MgO', 'cement', 'Carbonates during curing; lower embodied carbon', 'Mag Industries'),
('Calcium sulfoaluminate cement', 'cement', 'Rapid set; lower embodied carbon than OPC', 'CTS Cement'),
('Mycelium structural blocks', 'biofabricated', 'R&D stage; compressive strength improving rapidly', 'Ecovative Design'),
('Reclaimed glass insulation', 'reclaimed', 'Foam glass aggregate and board from recycled glass', 'Misapor'),
('Upcycled denim insulation', 'reclaimed', 'Cotton fiber batts; no VOCs; safe to handle', 'Bonded Logic'),
('Post-consumer carpet tile', 'reclaimed', 'Take-back programs from Interface and Shaw', 'Interface'),
('Sheep wool insulation', 'insulation', 'Hygroscopic; non-toxic; naturally fire resistant', 'Black Mountain Insulation'),
('Lime-pozzolan render', 'earth', 'Carbonates CO2 over its lifetime', 'Limeworks'),
('Natural hydraulic lime render', 'earth', 'Breathable; compatible with timber and masonry', 'St Astier'),
('Compressed earth blocks CEB', 'earth', 'Soil dependent; viable in Michigan clay soils', 'Hydraform'),
('Rammed earth stabilized', 'earth', 'High thermal mass; cold-climate design required', 'RECO Walls'),
('Tadelakt lime plaster', 'earth', 'Polished waterproof lime finish; traditional technique', 'Various'),
('Electrochromic glazing', 'windows', 'Dynamic tint reduces HVAC load significantly', 'Sage Glass'),
('Thermochromic coatings', 'cladding', 'Passive solar management through color change', 'Various'),
('Photocatalytic concrete TiO2', 'cement', 'Air purifying surface; reduces NOx in urban environments', 'TX Active'),
('Biocomposite cladding flax resin', 'cladding', 'Flax grown in Midwest; natural fiber composite panel', 'Bcomp'),
('Recycled tire crumb flooring', 'reclaimed', 'High supply; durable athletic and commercial surfaces', 'Dodge-Regupol'),
('Wood fiber batt insulation', 'insulation', 'Hygroscopic; moisture buffering in cold climates', 'Steico'),
('Insulated concrete forms ICF', 'insulation', 'High thermal mass plus R-value; proven cold climate', 'Nudura'),
('Roman pozzolanic lime mix', 'cement', 'Volcanic ash and lime; exceptional long-term durability', 'Various'),
('Reclaimed dimensional lumber 2', 'reclaimed', 'Old growth density and stability from salvage', 'Duluth Timber'),
('Recycled plastic lumber', 'reclaimed', 'Non-structural; durable decking and site furniture', 'Trex'),
('Shape memory polymer insulation', 'insulation', 'R&D stage; deployment timeline unclear', 'Various'),
('Bacterial cellulose composites', 'biofabricated', 'University stage; not yet commercially deployable', 'Various'),
('Chitin composite panels', 'biofabricated', 'Crustacean-derived; experimental material', 'Various'),
('Laminated bamboo lumber', 'timber', 'Import dependent; high carbon sequestration', 'MOSO International')
on conflict (name, category) do nothing;

-- Phase 2: insert RIS/LIS scores for the newly inserted materials
insert into public.lis_ris_scores (material_id, ris_score, lis_score, calculation_version, calculation_date, baseline_region)
select m.id,
       s.ris_score,
       s.lis_score,
       '1.0',
       current_date,
       'Great Lakes'
from (values
  ('Hempcrete','insulation',92,55),
  ('Cross-laminated timber (CLT)','timber',88,75),
  ('Thermally modified timber','timber',85,70),
  ('Alkali-activated slag cement','cement',85,65),
  ('Geopolymer concrete','cement',83,62),
  ('Ferrock','cement',91,45),
  ('Aerogel insulation blanket','insulation',72,82),
  ('Wood fiber insulation board','insulation',85,78),
  ('Hemp fiber insulation','insulation',92,60),
  ('Reclaimed structural steel','reclaimed',85,80),
  ('Mycelium panels','biofabricated',90,40),
  ('Lime-hemp plaster system','earth',91,55),
  ('Straw bale construction','timber',93,42),
  ('Cellulose insulation dense pack','insulation',86,79),
  ('Reclaimed brick','reclaimed',84,81),
  ('Biochar-amended concrete','cement',91,55),
  ('Agricultural fiber panels','insulation',92,45),
  ('Earthen plaster systems','earth',93,42),
  ('Phase-change material wallboard','insulation',72,65),
  ('Vacuum insulated panels','insulation',71,83),
  ('Recycled concrete aggregate','reclaimed',83,70),
  ('MgO board','cladding',83,63),
  ('Carbon-cured concrete blocks','cement',84,65),
  ('Cork insulation board','insulation',84,79),
  ('Bamboo structural composites','timber',91,60),
  ('Algae biopolymer panels','biofabricated',92,32),
  ('Self-healing concrete','cement',72,55),
  ('Natural hydraulic lime NHL','earth',83,60),
  ('Structural insulated panels SIP','insulation',84,80),
  ('Reclaimed dimensional lumber','reclaimed',84,81),
  ('Mass plywood panels MPP','timber',85,72),
  ('Acetylated wood Accoya','timber',83,68),
  ('Densified wood composites','timber',82,60),
  ('Myco-composite insulation','biofabricated',90,38),
  ('Belite calcite clinker cement','cement',83,58),
  ('Magnesium oxide cement MgO','cement',83,55),
  ('Calcium sulfoaluminate cement','cement',82,62),
  ('Mycelium structural blocks','biofabricated',89,35),
  ('Reclaimed glass insulation','reclaimed',72,68),
  ('Upcycled denim insulation','reclaimed',82,72),
  ('Post-consumer carpet tile','reclaimed',71,65),
  ('Sheep wool insulation','insulation',83,62),
  ('Lime-pozzolan render','earth',83,58),
  ('Natural hydraulic lime render','earth',83,60),
  ('Compressed earth blocks CEB','earth',83,45),
  ('Rammed earth stabilized','earth',83,45),
  ('Tadelakt lime plaster','earth',82,50),
  ('Electrochromic glazing','windows',71,65),
  ('Thermochromic coatings','cladding',71,52),
  ('Photocatalytic concrete TiO2','cement',71,58),
  ('Biocomposite cladding flax resin','cladding',83,55),
  ('Recycled tire crumb flooring','reclaimed',71,65),
  ('Wood fiber batt insulation','insulation',84,77),
  ('Insulated concrete forms ICF','insulation',83,78),
  ('Roman pozzolanic lime mix','cement',82,52),
  ('Reclaimed dimensional lumber 2','reclaimed',84,80),
  ('Recycled plastic lumber','reclaimed',71,62),
  ('Shape memory polymer insulation','insulation',70,40),
  ('Bacterial cellulose composites','biofabricated',91,30),
  ('Chitin composite panels','biofabricated',90,30),
  ('Laminated bamboo lumber','timber',90,58)
) as s(name, category, ris_score, lis_score)
join public.materials m on m.name = s.name and m.category = s.category
where not exists (
  select 1 from public.lis_ris_scores lrs where lrs.material_id = m.id
);
